PROFESSIONS = YAML.load_file("#{Rails.root}/config/data/professions.yml")
FACILITY_CATEGORIES = YAML.load_file("#{Rails.root}/config/data/facility_categories.yml")
OFFER_TYPES = YAML.load_file("#{Rails.root}/config/data/offer_types.yml")
OFFERS = YAML.load_file("#{Rails.root}/config/data/offers.yml")
DEPARTMENTS = YAML.load_file("#{Rails.root}/config/data/departments.yml")